# Generated by Django 4.2.1 on 2023-05-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.IntegerField()),
                ('marke', models.CharField(max_length=100)),
                ('modelis', models.CharField(max_length=100)),
                ('variklis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobilio_id', models.CharField(max_length=100)),
                ('klientas', models.CharField(max_length=100)),
                ('valstybinis_numeris', models.CharField(max_length=100)),
                ('vin_kodas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaisymoUzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bendra_suma', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atliktos_paslaugos', models.JSONField()),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisas.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='PaslaugosKaina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisas.paslauga')),
            ],
        ),
    ]
